import { createElement } from "react";
import {
  Activity,
  Anchor,
  Apple,
  Backpack,
  Battery,
  BatteryCharging,
  Bed,
  Beer,
  BicepsFlexed,
  Bone,
  BookOpen,
  Brain,
  Building2,
  CalendarDays,
  Car,
  Castle,
  Church,
  CircleDollarSign,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Coins,
  Compass,
  Cookie,
  Crown,
  Diamond,
  Drama,
  Droplet,
  Dumbbell,
  Eye,
  Factory,
  Feather,
  Flame,
  FlaskConical,
  Footprints,
  Gem,
  Ghost,
  Hammer,
  HandMetal,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Hourglass,
  Key,
  KeyRound,
  Landmark,
  Leaf,
  Lock,
  MapPin,
  Medal,
  Moon,
  Mountain,
  Music,
  Orbit,
  Package,
  Pickaxe,
  Pill,
  Pizza,
  Plane,
  Radiation,
  Sailboat,
  Scale,
  School,
  Scroll,
  Shield,
  ShieldCheck,
  Ship,
  Skull,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Stars,
  Store,
  Sun,
  Sword,
  Swords,
  Tag,
  Target,
  Tent,
  Thermometer,
  Train,
  TreePine,
  Trees,
  Trophy,
  Umbrella,
  User,
  Users,
  Utensils,
  VenetianMask,
  WalletCards,
  WandSparkles,
  Warehouse,
  Waves,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { SupportedStatIcon, SupportedWorldCustomFieldIcon } from "@marinara-engine/shared";
import { cn } from "../../lib/utils";

type SupportedConfiguredIcon = SupportedStatIcon | SupportedWorldCustomFieldIcon;

const CONFIGURED_LUCIDE_ICONS = {
  activity: Activity,
  anchor: Anchor,
  apple: Apple,
  backpack: Backpack,
  battery: Battery,
  "battery-charging": BatteryCharging,
  bed: Bed,
  beer: Beer,
  "biceps-flexed": BicepsFlexed,
  bone: Bone,
  "book-open": BookOpen,
  brain: Brain,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  car: Car,
  castle: Castle,
  church: Church,
  "circle-dollar-sign": CircleDollarSign,
  clock: Clock,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  cookie: Cookie,
  crown: Crown,
  diamond: Diamond,
  drama: Drama,
  droplet: Droplet,
  dumbbell: Dumbbell,
  eye: Eye,
  factory: Factory,
  feather: Feather,
  flame: Flame,
  "flask-conical": FlaskConical,
  footprints: Footprints,
  gem: Gem,
  ghost: Ghost,
  hammer: Hammer,
  "hand-metal": HandMetal,
  heart: Heart,
  "heart-pulse": HeartPulse,
  home: Home,
  hospital: Hospital,
  hourglass: Hourglass,
  key: Key,
  "key-round": KeyRound,
  landmark: Landmark,
  leaf: Leaf,
  lock: Lock,
  "map-pin": MapPin,
  medal: Medal,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  orbit: Orbit,
  package: Package,
  pickaxe: Pickaxe,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  radiation: Radiation,
  sailboat: Sailboat,
  scale: Scale,
  school: School,
  scroll: Scroll,
  shield: Shield,
  "shield-check": ShieldCheck,
  ship: Ship,
  skull: Skull,
  smile: Smile,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  stars: Stars,
  store: Store,
  sun: Sun,
  sword: Sword,
  swords: Swords,
  tag: Tag,
  target: Target,
  tent: Tent,
  thermometer: Thermometer,
  train: Train,
  "tree-pine": TreePine,
  trees: Trees,
  trophy: Trophy,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  "venetian-mask": VenetianMask,
  "wallet-cards": WalletCards,
  "wand-sparkles": WandSparkles,
  warehouse: Warehouse,
  waves: Waves,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<SupportedConfiguredIcon, LucideIcon>;

export function StatIcon({
  icon,
  size,
  className,
}: {
  icon: SupportedConfiguredIcon;
  size: string | number;
  className?: string;
}) {
  return createElement(CONFIGURED_LUCIDE_ICONS[icon], {
    size,
    className: cn("shrink-0", className),
  });
}
